dist: trusty
sudo: required
language: python
python:
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran libhdf5-serial-dev python-tables
  - sudo pip install -U pip
# command to install dependencies
install: "pip install -r requirements_dev.txt"
# command to run tests
script: pytest
