language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly" # currently points to 3.7-dev
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran libhdf5-serial-dev python-tables
  - pip install -U pip
# command to install dependencies
install: "pip install -r requirements_dev.txt"
# command to run tests
script: pytest
